jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.2-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
  checking:
    docker:
      - image: 'cimg/ruby:2.7.2-node'
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: 'cimg/ruby:2.7.2-node'
      - environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-demo-ruby
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:create db:schema:load --trace'
          name: Database setup
      - run: bundle exec rspec
orbs:
  node: circleci/node@4.1.0
  ruby: circleci/ruby@1.1.2
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
